/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "JNIDemoLog.h"
/* Header for class top_keepempty_jnindkdemo_JNIBaseUtils */

#ifndef _Included_top_keepempty_jnindkdemo_JNIBaseUtils
#define _Included_top_keepempty_jnindkdemo_JNIBaseUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_keepempty_jnindkdemo_JNIBaseUtils
 * Method:    passBooleanReturnBoolean
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_top_keepempty_jnindkdemo_JNIBaseUtils_passBooleanReturnBoolean
        (JNIEnv *, jobject, jboolean);

/*
 * Class:     top_keepempty_jnindkdemo_JNIBaseUtils
 * Method:    passByteReturnByte
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_top_keepempty_jnindkdemo_JNIBaseUtils_passByteReturnByte
        (JNIEnv *, jobject, jbyte);

/*
 * Class:     top_keepempty_jnindkdemo_JNIBaseUtils
 * Method:    passCharReturnChar
 * Signature: (C)C
 */
JNIEXPORT jchar JNICALL Java_top_keepempty_jnindkdemo_JNIBaseUtils_passCharReturnChar
        (JNIEnv *, jobject, jchar);

/*
 * Class:     top_keepempty_jnindkdemo_JNIBaseUtils
 * Method:    passShortReturnShort
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_top_keepempty_jnindkdemo_JNIBaseUtils_passShortReturnShort
        (JNIEnv *, jobject, jshort);

/*
 * Class:     top_keepempty_jnindkdemo_JNIBaseUtils
 * Method:    passIntReturnInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_top_keepempty_jnindkdemo_JNIBaseUtils_passIntReturnInt
        (JNIEnv *, jobject, jint);

/*
 * Class:     top_keepempty_jnindkdemo_JNIBaseUtils
 * Method:    passLongReturnLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_top_keepempty_jnindkdemo_JNIBaseUtils_passLongReturnLong
        (JNIEnv *, jobject, jlong);

/*
 * Class:     top_keepempty_jnindkdemo_JNIBaseUtils
 * Method:    passFloatReturnFloat
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_top_keepempty_jnindkdemo_JNIBaseUtils_passFloatReturnFloat
        (JNIEnv *, jobject, jfloat);

/*
 * Class:     top_keepempty_jnindkdemo_JNIBaseUtils
 * Method:    passDoubleReturnDouble
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_top_keepempty_jnindkdemo_JNIBaseUtils_passDoubleReturnDouble
        (JNIEnv *, jobject, jdouble);


/*
 * Class:     top_keepempty_jnindkdemo_JNIBaseUtils
 * Method:    passStringReturnString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_top_keepempty_jnindkdemo_JNIBaseUtils_passStringReturnString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
