/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_keepempty_jni_ndk_demo_JNIUtils */
#include "JNIDemoLog.h"
#ifndef _Included_top_keepempty_jnindkdemo_JNIUtils
#define _Included_top_keepempty_jnindkdemo_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_keepempty_jni_ndk_demo_JNIUtils
 * Method:    getString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jstring JNICALL Java_top_keepempty_jnindkdemo_JNIUtils_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
