/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "JNIDemoLog.h"
/* Header for class top_keepempty_jnindkdemo_JNICallJMUtils */

#ifndef _Included_top_keepempty_jnindkdemo_JNICallJMUtils
#define _Included_top_keepempty_jnindkdemo_JNICallJMUtils
#ifdef __cplusplus
extern "C" {
#endif

/*
* Class:     top_keepempty_jnindkdemo_JNICallJMUtils
* Method:    sayHello
* Signature: ()Ljava/lang/String;
*/
JNIEXPORT jstring JNICALL Java_top_keepempty_jnindkdemo_JNICallJMUtils_sayHello
        (JNIEnv *, jclass);
/*
 * Class:     top_keepempty_jnindkdemo_JNICallJMUtils
 * Method:    callJavaMethod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_top_keepempty_jnindkdemo_JNICallJMUtils_callJavaMethod
  (JNIEnv *, jclass, jint);

/*
 * Class:     top_keepempty_jnindkdemo_JNICallJMUtils
 * Method:    callJavaStaticMethod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_top_keepempty_jnindkdemo_JNICallJMUtils_callJavaStaticMethod
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
