/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_keepempty_jnindkdemo_JNIBaseUtils */

#ifndef _Included_top_keepempty_jnindkdemo_JNIBaseUtils
#define _Included_top_keepempty_jnindkdemo_JNIBaseUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_keepempty_jnindkdemo_JNIBaseUtils
 * Method:    passBooleanReturnBoolean
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_top_keepempty_jnindkdemo_JNIBaseUtils_passBooleanReturnBoolean
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     top_keepempty_jnindkdemo_JNIBaseUtils
 * Method:    passByteReturnByte
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_top_keepempty_jnindkdemo_JNIBaseUtils_passByteReturnByte
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     top_keepempty_jnindkdemo_JNIBaseUtils
 * Method:    passCharReturnChar
 * Signature: (C)C
 */
JNIEXPORT jchar JNICALL Java_top_keepempty_jnindkdemo_JNIBaseUtils_passCharReturnChar
  (JNIEnv *, jclass, jchar);

/*
 * Class:     top_keepempty_jnindkdemo_JNIBaseUtils
 * Method:    passShortReturnShort
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_top_keepempty_jnindkdemo_JNIBaseUtils_passShortReturnShort
  (JNIEnv *, jclass, jshort);

/*
 * Class:     top_keepempty_jnindkdemo_JNIBaseUtils
 * Method:    passIntReturnInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_top_keepempty_jnindkdemo_JNIBaseUtils_passIntReturnInt
  (JNIEnv *, jclass, jint);

/*
 * Class:     top_keepempty_jnindkdemo_JNIBaseUtils
 * Method:    passLongReturnLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_top_keepempty_jnindkdemo_JNIBaseUtils_passLongReturnLong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     top_keepempty_jnindkdemo_JNIBaseUtils
 * Method:    passFloatReturnFloat
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_top_keepempty_jnindkdemo_JNIBaseUtils_passFloatReturnFloat
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     top_keepempty_jnindkdemo_JNIBaseUtils
 * Method:    passDoubleReturnDouble
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_top_keepempty_jnindkdemo_JNIBaseUtils_passDoubleReturnDouble
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     top_keepempty_jnindkdemo_JNIBaseUtils
 * Method:    passStringReturnString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_top_keepempty_jnindkdemo_JNIBaseUtils_passStringReturnString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
