/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_keepempty_jnindkdemo_JNIRegUtils */

#ifndef _Included_top_keepempty_jnindkdemo_JNIRegUtils
#define _Included_top_keepempty_jnindkdemo_JNIRegUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_keepempty_jnindkdemo_JNIRegUtils
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_top_keepempty_jnindkdemo_JNIRegUtils_getString
  (JNIEnv *, jclass);

/*
 * Class:     top_keepempty_jnindkdemo_JNIRegUtils
 * Method:    printlnString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_top_keepempty_jnindkdemo_JNIRegUtils_printlnString
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     top_keepempty_jnindkdemo_JNIRegUtils
 * Method:    getTwoSum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_top_keepempty_jnindkdemo_JNIRegUtils_getTwoSum
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     top_keepempty_jnindkdemo_JNIRegUtils
 * Method:    init_confing_test
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_top_keepempty_jnindkdemo_JNIRegUtils_init_1confing_1test
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
